### ISSUE TITLE
IE11 crash

### ISSUE THREAD

**Issue by isachivka** [wavesplatform/waves-browser-bus#8]
Affected users:
```
Internet_Explorer@11.0
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
```

Callstack внутри waves-browser-bus:
```
node_modules/@waves/waves-browser-bus/dist/protocols/WindowProtocol.js:33:8
node_modules/@waves/waves-browser-bus/dist/adapters/WindowAdapter.js:51:52
node_modules/@waves/waves-browser-bus/dist/adapters/WindowAdapter.js:53:8
node_modules/@waves/waves-browser-bus/dist/bus/Bus.js:30:8
```

Iframe (для примера, падает кажется на любом dispatchEvent):
```
function* saga() {
  const adapter = yield WindowAdapter.createSimpleWindowAdapter();
  const bus = new Bus<events, handlers>(adapter);
  bus.dispatchEvent('ready', { message: 'blabla' });
}
```

В мою кибану прилетает текст ошибки: `Error: null`
Эксепшн происходит внутри айфрейма (не в parent)

Сам воспроизвести проблему в win10/ie11 не смог, но часть юзеров ловят эту ошибку

Если у вас есть идеи - буду рад, исправить смогу сам

**Comment by tsigel** [comment]
Добрый день. Эта проблема может быть связана со старыми ie (там нельзя передавать данные в событии в виде объекта, только строки). Попробуйте выставить флаг JSONMode, который передаёт данные в виде JSON. Этот режим сделан специально для старых ie, но там нельзя передавать некоторые типы данных (Uint8Array, FormData и прочее).

**Comment by isachivka** [comment]
@tsigel спасибо! Обязательно попробую и сброшу сюда результат если ошибки пропадут из кибаны
